name = "does module works?"
project= "logical-vim-376815"
region = "us-central1"
account_id = "account_id"
display_name = "display_name"
machine_type = "e2-medium"
zone = "us-central1-a"
image = "ubuntu-os-cloud/ubuntu-minimal-1804-lts"